---
name: coverage

on:
  push:
    branches:
      - master

jobs:
  codecoverage:
    runs-on: windows-2019
    name: Generate and upload code coverage
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Boost
      uses: MarkusJx/install-boost@v1.0.1
      id: install-boost
      with:
        boost_version: 1.79.0
    - name: Install packages
      run: cinst openssl opencppcoverage
    - name: Configure
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      shell: bash
      run: cmake -B build -DENABLE_DOCUMENTATION=OFF
    - name: Build
      run: cmake --build build/ --target unittest
    - name: Generate code coverage
      shell: bash
      run: exec "${PROGRAMFILES}"/opencppcoverage/opencppcoverage --cover_children --sources="${GITHUB_WORKSPACE}"\\include --modules=unittest.exe --export_type=cobertura:cobertura.xml -- ctest
      working-directory: build/
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        files: build/cobertura.xml
        fail_ci_if_error: true
